using System;
using System.Collections.Generic;

namespace WebApp.Models
{
    public class AB0039 : JCLib.Mvc.BaseModel
    {
        public string ORDERCODE { get; set; }
        public string INSUORDERCODE { get; set; }
        public string ORDERENGNAME { get; set; }
        public string SCIENTIFICNAME { get; set; }
        public string ORDERHOSPNAME { get; set; }
        public string ORDERCHINNAME { get; set; }
        public string ORDEREASYNAME { get; set; }
        public string COMMITTEECODE { get; set; }
        public string DRUGCLASSIFY { get; set; }
        public string ORDERUSETYPE { get; set; }
        public string ORDERCONDCODE { get; set; }
        public string DOHLICENSENO { get; set; }
        public string MULTIPRESCRIPTIONCODE { get; set; }
        public string DRUGELEMCODE1 { get; set; }
        public string COMPONENTNUNIT { get; set; }
        public string DRUGELEMCODE2 { get; set; }
        public string COMPONENTNUNIT2 { get; set; }
        public string DRUGELEMCODE3 { get; set; }
        public string COMPONENTNUNIT3 { get; set; }
        public string DRUGELEMCODE4 { get; set; }
        public string COMPONENTNUNIT4 { get; set; }
        public string ORDERUNIT { get; set; }
        public string ORDERCHINUNIT { get; set; }
        public string SUPPLYNO { get; set; }
        public string CONTRACNO { get; set; }
        public string CASEFROM { get; set; }
        public string INSUAMOUNT1 { get; set; }
        public string PAYAMOUNT1 { get; set; }
        public string BUYORDERFLAG { get; set; }
        public string CARRYKINDI { get; set; }
        public string CARRYKINDO { get; set; }
        public string AGGREGATECODE { get; set; }
        public string ORIGINALPRODUCER { get; set; }
        public string AGENTNAME { get; set; }
        public string SPECNUNIT { get; set; }
        public string ATTACHUNIT { get; set; }
        public string STOCKUNIT { get; set; }
        public string UDSERVICEFLAG { get; set; }
        public string LIMITEDQTYO { get; set; }
        public string LIMITEDQTYI { get; set; }
        public string PATHNO { get; set; }
        public string PUBLICDRUGCODE { get; set; }
        public string DRUGCLASS { get; set; }
        public string RESEARCHDRUGFLAG { get; set; }
        public string LIMITFLAG { get; set; }
        public string HOSPEXAMINEQTYFLAG { get; set; }
        public string RESTRICTTYPE { get; set; }
        public string MAXTAKETIMES { get; set; }
        public string MAXQTYO { get; set; }
        public string MAXDAYSO { get; set; }
        public string VALIDDAYSO { get; set; }
        public string MAXQTYI { get; set; }
        public string MAXDAYSI { get; set; }
        public string VALIDDAYSI { get; set; }
        public string FIXPATHNOFLAG { get; set; }
        public string TAKEKIND { get; set; }
        public string ANTIBIOTICSCODE { get; set; }
        public string RESTRICTCODE { get; set; }
        public string FREQNOI { get; set; }
        public string FREQNOO { get; set; }
        public string DOSE { get; set; }
        public string DOSE1 { get; set; }
        public string ORDERABLEDRUGFORM { get; set; }
        public string RAREDISORDERFLAG { get; set; }
        public string SPECIALORDERKIND { get; set; }
        public string HOSPEXAMINEFLAG { get; set; }
        public string MAXQTYPERTIME { get; set; }
        public string MAXQTYPERDAY { get; set; }
        public string ONLYROUNDFLAG { get; set; }
        public string UNABLEPOWDERFLAG { get; set; }
        public string COLDSTORAGEFLAG { get; set; }
        public string LIGHTAVOIDFLAG { get; set; }
        public string WEIGHTTYPE { get; set; }
        public string WEIGHTTYPE1 { get; set; }
        public string DANGERDRUGFLAG { get; set; }
        public string DANGERDRUGMEMO { get; set; }
        public string DRUGEXTERIOR { get; set; }
        public string DRUGENGEXTERIOR { get; set; }
        public string SYMPTOMCHIN { get; set; }
        public string SYMPTOMENG { get; set; }
        public string CHINSIDEEFFECT { get; set; }
        public string ENGSIDEEFFECT { get; set; }
        public string CHINATTENTION { get; set; }
        public string ENGATTENTION { get; set; }
        public string DOHLICENSENO1 { get; set; }
        public string FDASYMPTOM { get; set; }
        public string DRUGMEMO { get; set; }
        public string SUCKLESECURITY { get; set; }
        public string PREGNANTGRADE { get; set; }
        public string DRUGPICTURELINK { get; set; }
        public string DRUGLEAFLETLINK { get; set; }
        public string TDMFLAG { get; set; }
        public string TDMFLAG1 { get; set; }
        public string TDMFLAG2 { get; set; }
        public string TDMFLAG3 { get; set; }
        public string TDMFLAG4 { get; set; }
        public string TDMFLAG5 { get; set; }
        public string TDMFLAG6 { get; set; }
        public string TDMFLAG7 { get; set; }
        public string TDMFLAG8 { get; set; }
        public string TDMFLAG9 { get; set; }
        public string TDMFLAG10 { get; set; }
        public string TDMFLAG11 { get; set; }
        public string UDPOWDERFLAG { get; set; }
        public string MACHINEFLAG { get; set; }
        public string DRUGPARENTCODE1 { get; set; }
        public string DRUGPARENTCODE2 { get; set; }
        public string DRUGPARENTCODE3 { get; set; }
        public string DRUGPARENTCODE4 { get; set; }
        public string DRUGPACKAGE { get; set; }
        public string ATCCODE1 { get; set; }
        public string ATCCODE2 { get; set; }
        public string ATCCODE3 { get; set; }
        public string ATCCODE4 { get; set; }
        public string ATCCODE5 { get; set; }
        public string ATCCODE6 { get; set; }
        public string ATCCODE7 { get; set; }
        public string ATCCODE8 { get; set; }
        public string GERIATRIC { get; set; }
        public string LIVERLIMITED { get; set; }
        public string RENALLIMITED { get; set; }
        public string BIOLOGICALAGENT { get; set; }
        public string BLOODPRODUCT { get; set; }
        public string FREEZING { get; set; }
        public string RETURNDRUGFLAG { get; set; }
    }
}

