Ext.define('WEBAPP.model.AA0097M', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'CHECK_RESULT', type: 'string' },
        { name: 'IMPORT_RESULT', type: 'string' },
        { name: 'MMCODE', type: 'string' },
        { name: 'MMNAME', type: 'string' },
        { name: 'MMNAME_C', type: 'string' },
        { name: 'MMNAME_E', type: 'string' },
        { name: 'M_STOREID', type: 'string' },
        { name: 'DISC_UPRICE', type: 'string' },
        { name: 'M_PURUN', type: 'string' },
        { name: 'EXCH_RATIO', type: 'string' },
        { name: 'M_VOLL', type: 'string' },
        { name: 'M_VOLW', type: 'string' },
        { name: 'M_VOLH', type: 'string' },
        { name: 'M_VOLC', type: 'string' },
        { name: 'M_SWAP', type: 'string' },
        { name: 'M_IDKEY', type: 'string' },
        { name: 'M_INVKEY', type: 'string' },
        { name: 'M_GOVKEY', type: 'string' },
        { name: 'M_CONSUMID', type: 'string' },
        { name: 'M_PAYKIND', type: 'string' },
        { name: 'M_PAYID', type: 'string' },
        { name: 'M_TRNID', type: 'string' },
        { name: 'INV_POSTID', type: 'string' },
        { name: 'UPDATE_TIME', type: 'string' },
        { name: 'UPDATE_USER', type: 'string' },
        { name: 'UPDATE_IP', type: 'string' },
        { name: 'M_STOREID_N', type: 'string' },
        { name: 'DISC_UPRICE_N', type: 'string' },
        { name: 'M_PURUN_N', type: 'string' },
        { name: 'EXCH_RATIO_N', type: 'string' },
        { name: 'M_VOLL_N', type: 'string' },
        { name: 'M_VOLW_N', type: 'string' },
        { name: 'M_VOLH_N', type: 'string' },
        { name: 'M_VOLC_N', type: 'string' },
        { name: 'M_SWAP_N', type: 'string' },
        { name: 'M_IDKEY_N', type: 'string' },
        { name: 'M_INVKEY_N', type: 'string' },
        { name: 'M_GOVKEY_N', type: 'string' },
        { name: 'M_CONSUMID_N', type: 'string' },
        { name: 'M_PAYKIND_N', type: 'string' },
        { name: 'M_PAYID_N', type: 'string' },
        { name: 'M_TRNID_N', type: 'string' },
        //{ name: 'INV_POSTID_N', type: 'string' },
    ]
});