Ext.define('WEBAPP.model.AA0057M', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'ORDERCODE', type: 'string' },			//院內代碼
        { name: 'ORDERENGNAME', type: 'string' },			//英文名稱
        { name: 'ORDERCHINNAME', type: 'string' },			//中文名稱
        { name: 'SCIENTIFICNAME', type: 'string' },			//成份名稱
        { name: 'ORDERUNIT', type: 'string' },			//醫囑單位
        { name: 'ORDERCHINUNIT', type: 'string' },			//中文單位
        { name: 'ATTACHUNIT', type: 'string' },			//劑型單位
        { name: 'STOCKUNIT', type: 'string' },			//扣庫單位
        { name: 'SKORDERCODE', type: 'string' },			//藥品藥材代碼
        { name: 'UDSERVICEFLAG', type: 'string' },			//UD服務
        { name: 'TAKEKIND', type: 'string' },			//服用藥別
        { name: 'LIMITEDQTYO', type: 'string' },			//門診倍數核發
        { name: 'LIMITEDQTYI', type: 'string' },			//住院倍數核發
        { name: 'BUYORDERFLAG', type: 'string' },			//買斷藥
        { name: 'OPENDATE', type: 'string' },			//系統啟用日期
        { name: 'PUBLICDRUGFLAG', type: 'string' },			//公藥否(Y/N)
        { name: 'STARTDATE', type: 'string' },			//開始日期
        { name: 'ORDERHOSPNAME', type: 'string' },			//院內名稱
        { name: 'ORDEREASYNAME', type: 'string' },			//簡稱
        { name: 'INSUOFFERFLAG', type: 'string' },			//保險給付否(Y/N)
        { name: 'DCL', type: 'string' },			//DCL
        { name: 'APPENDMATERIALFLAG', type: 'string' },			//健保帶材料否
        { name: 'EXORDERFLAG', type: 'string' },			//特殊品項
        { name: 'ORDERDCFLAG', type: 'string' },			//停用碼
        { name: 'MAXQTYPERTIME', type: 'string' },			//一次極量
        { name: 'MAXQTYPERDAY', type: 'string' },			//一日極量
        { name: 'MAXTAKETIMES', type: 'string' },			//限制次數
        { name: 'DOHLICENSENO', type: 'string' },			//衛生署核准字號
        { name: 'RFIDCODE', type: 'string' },			//RFID條碼
        { name: 'PATHNO', type: 'string' },			//給藥途徑(部位)代碼
        { name: 'AGGREGATECODE', type: 'string' },			//累計用藥
        { name: 'LIMITFLAG', type: 'string' },			//開立專用限制
        { name: 'RESTRICTCODE', type: 'string' },			//管制用藥
        { name: 'ANTIBIOTICSCODE', type: 'string' },			//抗生素等級
        { name: 'CARRYKINDI', type: 'string' },			//住消耗歸整
        { name: 'CARRYKINDO', type: 'string' },			//門急消耗歸整
        { name: 'UDPOWDERFLAG', type: 'string' },			//UD磨粉
        { name: 'RETURNDRUGFLAG', type: 'string' },			//合理回流藥
        { name: 'RESEARCHDRUGFLAG', type: 'string' },			//研究用藥
        { name: 'MACHINEFLAG', type: 'string' },			//藥包機品項
        { name: 'TRANSCOMPUTEFLAG', type: 'string' },			//結轉計價
        { name: 'FIXPATHNOFLAG', type: 'string' },			//限制途徑Y/N
        { name: 'SYMPTOMCHIN', type: 'string' },			//適應症(中文)
        { name: 'SYMPTOMENG', type: 'string' },			//適應症(英文)
        { name: 'ONLYROUNDFLAG', type: 'string' },			//不可剝半
        { name: 'UNABLEPOWDERFLAG', type: 'string' },			//不可磨粉
        { name: 'DANGERDRUGFLAG', type: 'string' },			//高警訊藥品
        { name: 'DANGERDRUGMEMO', type: 'string' },			//高警訊藥品提示
        { name: 'COLDSTORAGEFLAG', type: 'string' },			//冷藏存放
        { name: 'LIGHTAVOIDFLAG', type: 'string' },			//避光存放
        { name: 'CHANGESTATUS', type: 'string' },			//異動狀態
        { name: 'FREQNOO', type: 'string' },			//門診給藥頻率
        { name: 'FREQNOI', type: 'string' },			//住院給藥頻率
        { name: 'ORDERDAYS', type: 'string' },			//預設開立天數
        { name: 'DOSE', type: 'string' },			//劑量
        { name: 'HOSPCHARGEID1', type: 'string' },			//院內費用類別
        { name: 'HOSPCHARGEID2', type: 'string' },			//院內費用
        { name: 'INSUCHARGEID1', type: 'string' },			//健保費用類別
        { name: 'INSUCHARGEID2', type: 'string' },			//健保費用
        { name: 'ORDERTYPE', type: 'string' },			//醫令類別
        { name: 'ORDERKIND', type: 'string' },			//醫令類別(申報定義)
        { name: 'HIGHPRICEFLAG', type: 'string' },			//高價用藥
        { name: 'CURETYPE', type: 'string' },			//特殊治療種類
        { name: 'INPDISPLAYFLAG', type: 'string' },			//住院醫囑顯示
        { name: 'SOONCULLFLAG', type: 'string' },			//開立醫令即為報到
        { name: 'SUBSTITUTE1', type: 'string' },			//替代院內代碼1
        { name: 'SUBSTITUTE2', type: 'string' },			//替代院內代碼2
        { name: 'SUBSTITUTE3', type: 'string' },			//替代院內代碼3
        { name: 'SUBSTITUTE4', type: 'string' },			//替代院內代碼4
        { name: 'SUBSTITUTE5', type: 'string' },			//替代院內代碼5
        { name: 'RELATEFLAGO', type: 'string' },			//連帶否(門診)
        { name: 'RELATEFLAGI', type: 'string' },			//連帶否(住院)
        { name: 'WEIGHTTYPE', type: 'string' },			//體重及安全量：計算別
        { name: 'WEIGHTUNITLIMIT', type: 'string' },			//體重及安全量：限制數量
        { name: 'RESTRICTTYPE', type: 'string' },			//限制狀態
        { name: 'MAXQTYO', type: 'string' },			//門診限制開立數量
        { name: 'MAXQTYI', type: 'string' },			//住院限制開立數量
        { name: 'MAXDAYSO', type: 'string' },			//門診限制開立日數
        { name: 'MAXDAYSI', type: 'string' },			//住院限制開立日數
        { name: 'VALIDDAYSO', type: 'string' },			//門診效期日數
        { name: 'VALIDDAYSI', type: 'string' },			//住院效期日數
        { name: 'CHECKINSWITCH', type: 'string' },			//是否需報到
        { name: 'REPORTFLAG', type: 'string' },			//是否發報告Y/N
        { name: 'SINGLEITEMFLAG', type: 'string' },			//SINGLEITEM
        { name: 'OPERATIONFLAG', type: 'string' },			//手術碼
        { name: 'EXAMINEDRUGFLAG', type: 'string' },			//檢驗用藥
        { name: 'MAINCUREITEM', type: 'string' },			//特定治療項目
        { name: 'RAYPOSITION', type: 'string' },			//放射部位
        { name: 'CCORDERCODE', type: 'string' },			//空針代碼
        { name: 'XRAYORDERCODE', type: 'string' },			//放射第二張代碼
        { name: 'ORDIAGCODE', type: 'string' },			//手術診斷碼
        { name: 'ORDERCODESORT', type: 'string' },			//醫令排序
        { name: 'SENDUNITFLAG', type: 'string' },			//傳送單位否
        { name: 'SIGNFLAG', type: 'string' },			//是否需SIGNIN
        { name: 'EXCLUDEFLAG', type: 'string' },			//除外項目
        { name: 'NEEDOPDTYPEFLAG', type: 'string' },			//處置需報調劑方式
        { name: 'DRUGELEMCODE1', type: 'string' },			//藥品成份ELEMENT1
        { name: 'DRUGELEMCODE2', type: 'string' },			//藥品成份ELEMENT2
        { name: 'DRUGELEMCODE3', type: 'string' },			//藥品成份ELEMENT3
        { name: 'DRUGELEMCODE4', type: 'string' },			//藥品成份ELEMENT4
        { name: 'CHANGEABLEFLAG', type: 'string' },			//可線上異動否
        { name: 'TDMFLAG', type: 'string' },			//TDM藥品
        { name: 'SPECIALORDERKIND', type: 'string' },			//專案碼
        { name: 'NEEDREGIONFLAG', type: 'string' },			//處置需報部位
        { name: 'ORDERUSETYPE', type: 'string' },			//醫令使用狀態
        { name: 'FIXDOSEFLAG', type: 'string' },			//預設劑量
        { name: 'RAREDISORDERFLAG', type: 'string' },			//罕見疾病用藥
        { name: 'HOSPEXAMINEFLAG', type: 'string' },			//內審用藥
        { name: 'ORDERCONDCODE', type: 'string' },			//給付條文代碼
        { name: 'HOSPEXAMINEQTYFLAG', type: 'string' },			//內審限制用量
        { name: 'CREATEDATETIME', type: 'string' },			//記錄建立日期/時間
        { name: 'CREATEOPID', type: 'string' },			//記錄建立人員
        { name: 'PROCDATETIME', type: 'string' },			//記錄處理日期/時間
        { name: 'PROCOPID', type: 'string' },			//記錄處理人員
        { name: 'HEPATITISCODE', type: 'string' },			//BC肝用藥註記
        //{ name: 'ORDERCODE', type: 'string' },			//院內代碼
        { name: 'BEGINDATE', type: 'string' },			//生效起日
        { name: 'ENDDATE', type: 'string' },			//生效迄日
        { name: 'STOCKTRANSQTYO', type: 'string' },			//門診扣庫轉換量
        { name: 'STOCKTRANSQTYI', type: 'string' },			//住院扣庫轉換量
        { name: 'ATTACHTRANSQTYO', type: 'string' },			//門診劑型數量
        { name: 'ATTACHTRANSQTYI', type: 'string' },			//住院劑型數量
        { name: 'INSUAMOUNT1', type: 'string' },			//健保點數一
        { name: 'INSUAMOUNT2', type: 'string' },			//健保點數二
        { name: 'PAYAMOUNT1', type: 'string' },			//自費點數一
        { name: 'PAYAMOUNT2', type: 'string' },			//自費點數二
        { name: 'COSTAMOUNT', type: 'string' },			//進價
        { name: 'MAMAGEFLAG', type: 'string' },			//是否收管理費
        { name: 'MAMAGERATE', type: 'string' },			//管理費%
        { name: 'INSUORDERCODE', type: 'string' },			//健保碼
        { name: 'INSUSIGNI', type: 'string' },			//健保負擔碼(住院)
        { name: 'INSUSIGNO', type: 'string' },			//健保負擔碼(門診)
        { name: 'INSUEMGFLAG', type: 'string' },			//健保急件加成
        { name: 'HOSPEMGFLAG', type: 'string' },			//自費急件加成
        { name: 'DENTALREFFLAG', type: 'string' },			//牙科轉診加成
        { name: 'PPFTYPE', type: 'string' },			//提成類別碼
        { name: 'PPFPERCENTAGE', type: 'string' },			//提成百分比
        { name: 'INSUKIDFLAG', type: 'string' },			//兒童加成否
        { name: 'HOSPKIDFLAG', type: 'string' },			//自費兒童加成
        { name: 'CONTRACTPRICE', type: 'string' },			//合約單價
        { name: 'CONTRACNO', type: 'string' },			//合約碼
        { name: 'SUPPLYNO', type: 'string' },			//廠商代碼(供應商代碼)
        { name: 'CASEFROM', type: 'string' },			//標案來源
        { name: 'EXAMINEDISCFLAG', type: 'string' },			//檢查折扣否
        { name: 'ORIGINALPRODUCER', type: 'string' },			//製造廠名稱
        { name: 'AGENTNAME', type: 'string' },			//申請商名稱
        //{ name: 'CREATEDATETIME', type: 'string' },			//記錄建立日期/時間
        //{ name: 'CREATEOPID', type: 'string' },			//記錄建立人員
        //{ name: 'PROCDATETIME', type: 'string' },			//記錄處理日期/時間
        //{ name: 'PROCOPID', type: 'string' },			//記錄處理人員
        { name: 'ENDDATETIME', type: 'string' },			//結束日期時間
    ]
});