Ext.define('WEBAPP.model.AA0059M', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'WH_NO', type: 'string' },
        { name: 'MMCODE', type: 'string' },
        { name: 'CREATE_TIME', type: 'string' },
        { name: 'CREATE_USER', type: 'string' },
        { name: 'UPDATE_TIME', type: 'string' },
        { name: 'UPDATE_USER', type: 'string' },
        { name: 'UPDATE_IP', type: 'string' },
        { name: 'ITEM_STRING', type: 'string' },
        { name: 'WH_KIND', type: 'string' },
        { name: 'WH_GRADE', type: 'string' },
        { name: 'WH_NAME', type: 'string' },
        { name: 'MMNAME_E', type: 'string' },
        { name: 'MMNAME_C', type: 'string' },
        { name: 'E_DRUGCLASS', type: 'string' },
        { name: 'E_DRUGCLASSIFY', type: 'string' },
        { name: 'E_SOURCECODE', type: 'string' },
        { name: 'E_DRUGAPLTYPE', type: 'string' },
        { name: 'E_MANUFACT', type: 'string' },
        { name: 'WH_GRADE_D', type: 'string' },
        { name: 'WH_KIND_D', type: 'string' },
        { name: 'E_DRUGCLASS_D', type: 'string' },
        { name: 'E_DRUGCLASSIFY_D', type: 'string' },
        { name: 'E_SOURCECODE_D', type: 'string' },
        { name: 'E_DRUGAPLTYPE_D', type: 'string' },
        { name: 'M_AGENLAB', type: 'string' },
    ]
});