Ext.define('WEBAPP.model.AA0104M', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'WH_NO', type: 'string' },           //單位代碼,
        { name: 'WH_NAME', type: 'string' },         //單位名稱,
        { name: 'DATA_YM', type: 'string' },         //成本年月,
        { name: 'MMCODE', type: 'string' },          //院內碼,
        { name: 'MMNAME_C', type: 'string' },            //中文品名,
        { name: 'MMNAME_E', type: 'string' },            //英文品名,
        { name: 'BASE_UNIT', type: 'string' },           //計量單位,
        { name: 'PMN_AVGPRICE', type: 'string' },            //期初單價,
        { name: 'P_INV_QTY', type: 'string' },           //期初結存,
        { name: 'SUM1', type: 'string' },            //期初金額,
        { name: 'IN_PRICE', type: 'string' },            //進貨單價,
        { name: 'IN_QTY', type: 'string' },          //本月進貨,
        { name: 'SUM2', type: 'string' },            //進貨金額,
        { name: 'AVG_PRICE', type: 'string' },           //消耗單價,本月單價,
        { name: 'OUT_QTY', type: 'string' },         //本月消耗,
        { name: 'SUM3', type: 'string' },            //消耗金額,
        { name: 'INV_QTY', type: 'string' },         //本月結存,
        { name: 'SUMTOT', type: 'string' },          //結存金額,
        { name: 'INVENTORYQTY', type: 'string' },            //盤盈虧數量,
        { name: 'SUM4', type: 'string' }			//盤盈虧金額,
    ]
});