Ext.define('WEBAPP.model.AB0089_1', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'OrderCode', type: 'string' }, 
        { name: 'ProcDateTime', type: 'string' }, 
        { name: 'ProcOpID', type: 'string' }, 
        { name: 'OrderEngName', type: 'string' } ,
        { name: 'OrderChinName', type: 'string' } ,
        { name: 'ScientificName', type: 'string' } ,
        { name: 'OrderUnit', type: 'string' } ,
        { name: 'OrderChinUnit', type: 'string' } ,
        { name: 'AttachUnit', type: 'string' } ,
        { name: 'StockUnit', type: 'string' } ,
        { name: 'SkOrderCode', type: 'string' } ,
        { name: 'UDServiceFlag', type: 'string' } ,
        { name: 'TakeKind', type: 'string' } ,
        { name: 'LimitedQtyO', type: 'string' } ,
        { name: 'LimitedQtyI', type: 'string' } ,
        { name: 'BuyOrderFlag', type: 'string' } ,
        { name: 'OpenDate', type: 'string' } ,
        { name: 'PublicDrugFlag', type: 'string' } ,
        { name: 'StartDate', type: 'string' } ,
        { name: 'OrderHospName', type: 'string' } ,
        { name: 'OrderEasyName', type: 'string' } ,
        { name: 'OrderDCFlag', type: 'string' } ,
        { name: 'MaxQtyPerTime', type: 'string' } ,
        { name: 'MaxQtyPerDay', type: 'string' } ,
        { name: 'MaxTakeTimes', type: 'string' } ,
        { name: 'DOHLicenseNo', type: 'string' } ,
        { name: 'RFIDCode', type: 'string' } ,
        { name: 'PathNo', type: 'string' } ,
        { name: 'AggregateCode', type: 'string' } ,
        { name: 'LimitFlag', type: 'string' } ,
        { name: 'RestrictCode', type: 'string' } ,
        { name: 'AntibioticsCode', type: 'string' } ,
        { name: 'CarryKindI', type: 'string' } ,
        { name: 'CarryKindO', type: 'string' } ,
        { name: 'UDPowderFlag', type: 'string' } ,
        { name: 'ReturnDrugFlag', type: 'string' } ,
        { name: 'ResearchDrugFlag', type: 'string' } ,
        { name: 'MachineFlag', type: 'string' } ,
        { name: 'FixPathNoFlag', type: 'string' } ,
        { name: 'SymptomChin', type: 'string' } ,
        { name: 'SymptomEng', type: 'string' } ,
        { name: 'OnlyRoundFlag', type: 'string' } ,
        { name: 'UnablePowderFlag', type: 'string' } ,
        { name: 'DangerDrugFlag', type: 'string' } ,
        { name: 'DangerDrugMemo', type: 'string' } ,
        { name: 'ColdStorageFlag', type: 'string' } ,
        { name: 'LightAvoidFlag', type: 'string' } ,
        { name: 'ChangeStatus', type: 'string' } ,
        { name: 'FreqNoO', type: 'string' } ,
        { name: 'FreqNoI', type: 'string' } ,
        { name: 'OrderDays', type: 'string' } ,
        { name: 'Dose', type: 'string' } ,
        { name: 'HospChargeID1', type: 'string' } ,
        { name: 'OrderType', type: 'string' } ,
        { name: 'OrderKind', type: 'string' } ,
        { name: 'HighPriceFlag', type: 'string' } ,
        { name: 'InpDisplayFlag', type: 'string' } ,
        { name: 'Substitute1', type: 'string' } ,
        { name: 'Substitute2', type: 'string' } ,
        { name: 'Substitute3', type: 'string' } ,
        { name: 'Substitute4', type: 'string' } ,
        { name: 'Substitute5', type: 'string' } ,
        { name: 'WeightType', type: 'string' } ,
        { name: 'WeightUnitLimit', type: 'string' } ,
        { name: 'RestrictType', type: 'string' } ,
        { name: 'MaxQtyO', type: 'string' } ,
        { name: 'MaxQtyI', type: 'string' } ,
        { name: 'MaxDaysO', type: 'string' } ,
        { name: 'MaxDaysI', type: 'string' } ,
        { name: 'ValidDaysO', type: 'string' } ,
        { name: 'ValidDaysI', type: 'string' } ,
        { name: 'OrderCodeSort', type: 'string' } ,
        { name: 'DrugElemCode1', type: 'string' } ,
        { name: 'DrugElemCode2', type: 'string' } ,
        { name: 'DrugElemCode3', type: 'string' } ,
        { name: 'DrugElemCode4', type: 'string' } ,
        { name: 'TDMFlag', type: 'string' } ,
        { name: 'SpecialOrderKind', type: 'string' } ,
        { name: 'NeedRegionFlag', type: 'string' } ,
        { name: 'OrderUseType', type: 'string' } ,
        { name: 'FixDoseFlag', type: 'string' } ,
        { name: 'RareDisorderFlag', type: 'string' } ,
        { name: 'HospExamineFlag', type: 'string' } ,
        { name: 'OrderCondCode', type: 'string' } ,
        { name: 'HospExamineQtyFlag', type: 'string' } ,
        { name: 'CreateDateTime', type: 'string' } ,
        { name: 'CreateOpID', type: 'string' } 
    ]
});