Ext.define('WEBAPP.model.AB0120M', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'MAT_CLASS', type: 'string' },
        { name: 'MMCODE', type: 'string' },
        { name: 'MMNAME', type: 'string' },
        { name: 'EX_INV_QTY', type: 'string' },
        { name: 'INV_QTY', type: 'string' },
        { name: 'BASE_UNIT', type: 'string' },
        { name: 'M_CONTID', type: 'string' },
        { name: 'MMNAME_C', type: 'string' },
        { name: 'MMNAME_E', type: 'string' },
        { name: 'MAT_CLASS', type: 'string' },
        { name: 'MIL', type: 'string' },
        { name: 'DATA_YM', type: 'string' },
        { name: 'M_AGENNO', type: 'string' },
        { name: 'AGEN_NAMEC', type: 'string' },
        { name: 'CREATE_DATE', type: 'string' },
        { name: 'CREATE_USER', type: 'string' },
        { name: 'UPDATE_DATE', type: 'string' },
        { name: 'UPDATE_USER', type: 'string' },
        { name: 'UPDATE_IP', type: 'string' },
        { name: 'WH_NO', type: 'string' }, //單位代碼",
        { name: 'WH_NAME', type: 'string' }, //單位名稱",
        { name: 'SUM1', type: 'string' }, //上月結存金額",
        { name: 'SUM2', type: 'string' }, //本月進貨金額",
        { name: 'SUM3', type: 'string' }, //本月消耗金額",
        { name: 'SUMTOT', type: 'string' }, //本月結存金額",
        { name: 'SUM4', type: 'string' }, //本月盈虧金額",
        { name: 'RAT', type: 'string' }, //期末比值",
    ]
});