Ext.define('WEBAPP.model.BA0005M', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'FLOWID', type: 'string' },
        { name: 'DOCTYPE', type: 'string' },
        { name: 'FLOWNAME', type: 'string' },
        { name: 'SATUSCODE', type: 'string' },
        { name: 'FLOWID1', type: 'string' },
        { name: 'FLOWBTN1', type: 'string' },
        { name: 'FLOWID2', type: 'string' },
        { name: 'FLOWBTN2', type: 'string' },
        { name: 'FLOWID3', type: 'string' },
        { name: 'FLOWBTN3', type: 'string' },
        { name: 'TR_ID', type: 'string' },
        { name: 'TR_FLOWID', type: 'string' },
        { name: 'TR_FLOWID1', type: 'string' },
        { name: 'TR_KIND', type: 'string' },
        { name: 'CREATE_TIME', type: 'string' },
        { name: 'CREATE_USER', type: 'string' },
        { name: 'UPDATE_TIME', type: 'string' },
        { name: 'UPDATE_USER', type: 'string' },
        { name: 'UPDATE_IP', type: 'string' },
        { name: 'DOCNO', type: 'string' },
        { name: 'SEQ', type: 'string' },
        { name: 'MMCODE', type: 'string' },
        { name: 'APPQTY', type: 'string' },
        { name: 'APVQTY', type: 'string' },
        { name: 'APVTIME', type: 'string' },
        { name: 'APVID', type: 'string' },
        { name: 'ACKQTY', type: 'string' },
        { name: 'ACKID', type: 'string' },
        { name: 'ACKTIME', type: 'string' },
        { name: 'STAT', type: 'string' },
        { name: 'RDOCNO', type: 'string' },
        { name: 'RSEQ', type: 'string' },
        { name: 'EXPT_DISTQTY', type: 'string' },
        { name: 'DIS_USER', type: 'string' },
        { name: 'DIS_TIME', type: 'string' },
        { name: 'BW_MQTY', type: 'string' },
        { name: 'BW_SQTY', type: 'string' },
        { name: 'PICK_QTY', type: 'string' },
        { name: 'PICK_USER', type: 'string' },
        { name: 'PICK_TIME', type: 'string' },
        { name: 'ONWAY_QTY', type: 'string' },
        { name: 'APL_CONTIME', type: 'string' },
        { name: 'AMT', type: 'string' },
        { name: 'UP', type: 'string' },
        { name: 'R1', type: 'string' },
        { name: 'R2', type: 'string' },
        { name: 'APLYITEM_NOTE', type: 'string' },
    ]
});