Ext.define('WEBAPP.model.FA0007M', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'MMCODE', type: 'string' }, //院內碼,
        { name: 'MAT_CLASS', type: 'string' }, //物料分類,
        { name: 'MMNAME_C', type: 'string' }, //中文品名,
        { name: 'MMNAME_E', type: 'string' }, //英文品名,
        { name: 'BASE_UNIT', type: 'string' }, //計量單位,
        { name: 'AVG_PRICEA', type: 'string' }, //期末單價(軍),
        { name: 'AVG_PRICEB', type: 'string' }, //期末單價(民),
        { name: 'INV_QTYA', type: 'string' }, //調整前戰備存量, //調整後戰備存量,
        { name: 'PINV_QTYB', type: 'string' }, //調整前民品存量,
        { name: 'PINVQTY', type: 'string' }, //調整前期末存量,
        { name: 'SUM1A', type: 'string' }, //調整前期末戰備成本,
        { name: 'SUM1B', type: 'string' }, //調整前期末民品成本,
        { name: 'SUM1', type: 'string' }, //調整前期末成本,
        //{ name: 'AVG_PRICEB', type: 'string' }, //期末單價(民),
        { name: 'INVENTORYQTY', type: 'string' }, //民品盤點總量,
        { name: 'SUM2', type: 'string' }, //盤盈虧金額,
        //{ name: 'AVG_PRICEA', type: 'string' }, //期末單價(軍),
        //{ name: 'AVG_PRICEB', type: 'string' }, //期末單價(民),
        //{ name: 'INV_QTYA', type: 'string' }, //調整後戰備存量,
        { name: 'INV_QTYB', type: 'string' }, //調整後民品存量,
        { name: 'INVQTY', type: 'string' }, //調整後期末存量,
        { name: 'SUM4A', type: 'string' }, //調整後期末戰備成本,
        { name: 'SUM4B', type: 'string' }, //調整後期末民品成本,
        { name: 'SUM4', type: 'string' }, //調整後期末成本,
        { name: 'RAT', type: 'string' }, //期末比值,
    ]
});