Ext.define('WEBAPP.model.FA0006M', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'MMCODE', type: 'string' }, //院內碼,
        { name: 'MAT_CLASS', type: 'string' }, //物料分類,
        { name: 'MMNAME_C', type: 'string' }, //中文品名,
        { name: 'MMNAME_E', type: 'string' }, //英文品名,
        { name: 'BASE_UNIT', type: 'string' }, //計量單位,
        { name: 'PMN_AVGPRICEA', type: 'string' }, //上期結存單價(軍),
        { name: 'PMN_AVGPRICEB', type: 'string' }, //上期結存單價(民),
        { name: 'PINV_QTYA', type: 'string' }, //期初戰備存量,
        { name: 'PINV_QTYB', type: 'string' }, //期初民品存量,
        { name: 'PINVQTY', type: 'string' }, //期初合計存量,
        { name: 'SUM1A', type: 'string' }, //期初戰備成本,
        { name: 'SUM1B', type: 'string' }, //期初民品成本,
        { name: 'SUM1', type: 'string' }, //期初成本,
        { name: 'IN_PRICE', type: 'string' }, //進貨單價,
        { name: 'IN_QTYA', type: 'string' }, //戰備進貨量,
        { name: 'IN_QTYB', type: 'string' }, //民品進貨量,
        { name: 'INQTY', type: 'string' }, //合計進貨量,
        { name: 'SUM2A', type: 'string' }, //戰備進貨成本,
        { name: 'SUM2B', type: 'string' }, //民品進貨成本,
        { name: 'SUM2', type: 'string' }, //進貨成本,
        { name: 'AVG_PRICEA', type: 'string' }, //消耗單價(軍), //期末單價(軍),
        { name: 'AVG_PRICEB', type: 'string' }, //消耗單價(民), //期末單價(民),
        { name: 'OUT_QTYA', type: 'string' }, //戰備消耗量,
        { name: 'OUT_QTYB', type: 'string' }, //民品消耗量,
        { name: 'OUTQTY', type: 'string' }, //合計消耗量,
        { name: 'SUM3A', type: 'string' }, //戰備消耗成本,
        { name: 'SUM3B', type: 'string' }, //民品消耗成本,
        { name: 'SUM3', type: 'string' }, //消耗成本,
        { name: 'INV_QTYA', type: 'string' }, //期末戰備存量,
        { name: 'INV_QTYB', type: 'string' }, //期末民品存量,
        { name: 'INVQTY', type: 'string' }, //期末合計存量,
        { name: 'SUM4A', type: 'string' }, //期末戰備成本,
        { name: 'SUM4B', type: 'string' }, //期末民品成本,
        { name: 'SUM4', type: 'string' }, //期末成本,
    ]
});