Ext.define('WEBAPP.model.HIS_CONSUME_D', {
    extend: 'Ext.data.Model',
    fields: [
        { 'name': 'DATA_DATE ', type: 'string' },
        { 'name': 'DATA_BTIME ', type: 'string' },
        { 'name': 'DATA_ETIME ', type: 'string' },
        { 'name': 'STOCKCODE ', type: 'string' },
        { 'name': 'WH_NAME ', type: 'string' },
        { 'name': 'ORDERCODE ', type: 'string' },
        { 'name': 'MMNAME_E ', type: 'string' },
        { 'name': 'VISIT_KIND ', type: 'string' },
        { 'name': 'STOCKFLAG ', type: 'string' },
        { 'name': 'ORDERDR ', type: 'string' },
        { 'name': 'MEDNO ', type: 'string' },
        { 'name': 'VISITDATE ', type: 'string' },
        { 'name': 'RID ', type: 'string' },
        { 'name': 'WORKDATE ', type: 'string' },
        { 'name': 'WORKTIME ', type: 'string' },
        { 'name': 'MODIFYDATE ', type: 'string' },
        { 'name': 'MODIFYTIME ', type: 'string' },
        { 'name': 'CANCELDATETIME ', type: 'string' },
        { 'name': 'SECTIONNO ', type: 'string' },
        { 'name': 'VSDR ', type: 'string' },
        { 'name': 'INSULOOKSEQ ', type: 'string' },
        { 'name': 'DOSE ', type: 'string' },
        { 'name': 'FREQNO ', type: 'string' },
        { 'name': 'PATHNO ', type: 'string' },
        { 'name': 'DAYS ', type: 'string' },
        { 'name': 'SUMQTY ', type: 'string' },
        { 'name': 'EMGFLAG ', type: 'string' },
        { 'name': 'REGION ', type: 'string' },
        { 'name': 'PAYFLAG ', type: 'string' },
        { 'name': 'COMPUTECODE ', type: 'string' },
        { 'name': 'ADDRATIO1 ', type: 'string' },
        { 'name': 'ADDRATIO2 ', type: 'string' },
        { 'name': 'ADDRATIO3 ', type: 'string' },
        { 'name': 'INSUCHARGEID ', type: 'string' },
        { 'name': 'HOSPCHARGEID ', type: 'string' },
        { 'name': 'INSUAMOUNT ', type: 'string' },
        { 'name': 'PAYAMOUNT ', type: 'string' },
        { 'name': 'CANCELFLAG ', type: 'string' },
        { 'name': 'CANCELOPID ', type: 'string' },
        { 'name': 'PROCOPID ', type: 'string' },
        { 'name': 'PROCDATETIME ', type: 'string' },
        { 'name': 'CREATEOPID ', type: 'string' },
        { 'name': 'CREATEDATETIME ', type: 'string' },
        { 'name': 'DRUGNO ', type: 'string' },
        { 'name': 'SLOWCARD ', type: 'string' }
    ]
});