Ext.define('WEBAPP.model.ME_BACK', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'MEDNO', type: 'string' },
        { name: 'CHINNAME', type: 'string' },
        { name: 'NRCODE', type: 'string' },
        { name: 'BEDNO', type: 'string' },
        { name: 'ORDERCODE', type: 'string' },
        { name: 'ORDERENGNAME', type: 'string' },
        { name: 'BEGINDATETIME', type: 'string' },
        { name: 'ENDDATETIME', type: 'string' },
        { name: 'DOSE', type: 'string' },
        { name: 'FREQNO', type: 'string' },
        { name: 'NEEDBACKQTY', type: 'string' },
        { name: 'BACKQTY', type: 'string' },
        { name: 'DIFF', type: 'string' },
        { name: 'PHRBACKREASON', type: 'string' },
        { name: 'CREATEDATETIME', type: 'string' },
        { name: 'CREATEOPID', type: 'string' },
        { name: 'CHARTNO', type: 'string' },
        { name: 'STOCKUNIT', type: 'string' },
        { name: 'ORDERNO', type: 'string' },
        { name: 'INSUAMOUNT1', type: 'string' },
        { name: 'PAYAMOUNT1', type: 'string' },
        { name: 'BACKNAME', type: 'string' },
        { name: 'ORDERUNIT', type: 'string' },
        { name: 'RETURNSTOCKCODE', type: 'string' },
        { name: 'USEDATETIME', type: 'string' },
        { name: 'RDOCNO', type: 'string' },
        { name: 'RSEQ', type: 'string' },
        { name: 'PHRBACKREASON_NAME', type: 'string' }, 
        { name: 'ORDERSORT', type: 'string' }
    ]
});