Ext.define('WEBAPP.model.MM_PR_D', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'MMCODE', type: 'string' },
        { name: 'PR_NO', type: 'string' },
        { name: 'AGEN_FAX', type: 'string' },
        { name: 'AGEN_NAME', type: 'string' },
        { name: 'AGEN_NO', type: 'string' },
        { name: 'BW_SQTY', type: 'string' },
        { name: 'BASE_UNIT', type: 'string' },        
        { name: 'DELI_QTY', type: 'string' },
        { name: 'DISC', type: 'string' },
        { name: 'IS_FAX', type: 'string' },
        { name: 'IS_MAIL', type: 'string' },
        { name: 'M_CONTID', type: 'string' },
        { name: 'M_CONTPRICE', type: 'string' },
        { name: 'M_PURUN', type: 'string' },
        { name: 'PO_NO', type: 'string' },
        { name: 'PR_PRICE', type: 'string' },
        { name: 'PR_QTY', type: 'string' },
        { name: 'REQ_QTY_T', type: 'string' },
        { name: 'UNIT_SWAP', type: 'string' },
        { name: 'CREATE_TIME', type: 'string' },
        { name: 'CREATE_USER', type: 'string' },
        { name: 'UPDATE_IP', type: 'string' },
        { name: 'UPDATE_TIME', type: 'string' },
        { name: 'UPDATE_USER', type: 'string' },
        { name: 'UPRICE', type: 'string' },
        { name: 'TOTAL_PRICE', type: 'string' },
        { name: 'TOT', type: 'string' },
        { name: 'INV_QTY', type: 'string' },
     ]
});