Ext.define('WEBAPP.model.MM_PO_D', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'PO_NO', type: 'string' },
        { name: 'MMCODE', type: 'string' },
        { name: 'PR_DEPT', type: 'date' },
        { name: 'PO_QTY', type: 'string' },
        { name: 'PO_PRICE', type: 'string' },
        { name: 'M_PURUN', type: 'string' },
        { name: 'M_AGENLAB', type: 'string' },
        { name: 'PO_AMT', type: 'string' },
        { name: 'M_DISCPERC', type: 'string' },
        { name: 'DELI_QTY', type: 'string' },
        { name: 'BW_QTY', type: 'string' },
        { name: 'DELI_STATUS', type: 'string' },
        { name: 'BW_QTY', type: 'string' },
        { name: 'CREATE_TIME', type: 'string' },
        { name: 'CREATE_USER', type: 'string' },
        { name: 'UPDATE_TIME', type: 'string' },
        { name: 'UPDATE_USER', type: 'string' },
        { name: 'UPDATE_IP', type: 'string' },
        { name: 'MEMO', type: 'string' },
        { name: 'PR_NO', type: 'string' },
        { name: 'UNIT_SWAP', type: 'string' }, 
        { name: 'INVOICE', type: 'string' },
        { name: 'INVOICE_DT', type: 'string' },
        { name: 'CKIN_QTY', type: 'string' },
        { name: 'CHK_USER', type: 'string' },
        { name: 'CHK_DT', type: 'string' },
        { name: 'AGEN_NO', type: 'string' }
    ]
});