Ext.define('WEBAPP.model.PhSmallM', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'DN', type: 'string' },
        { name: 'ACCEPT', type: 'string' },
        { name: 'AGEN_NAMEC', type: 'string' },
        { name: 'AGEN_NO', type: 'string' },
        { name: 'ALT', type: 'string' },
        { name: 'APP_INID', type: 'string' },
        { name: 'APP_USER', type: 'string' },
        { name: 'APP_USER1', type: 'string' },
        { name: 'APPTIME', type: 'date' },
        { name: 'APPTIME1', type: 'date' },
        { name: 'DELIVERY', type: 'string' },
        { name: 'DEMAND', type: 'string' },
        { name: 'DEPT', type: 'string' },
        { name: 'DO_USER', type: 'string' },
        { name: 'DOTEL', type: 'string' },
        { name: 'DUEDATE', type: 'string' },
        { name: 'OTHERS', type: 'string' },
        { name: 'PAYWAY', type: 'string' },
        { name: 'PR_NO', type: 'string' },
        { name: 'REASON', type: 'string' },
        { name: 'STATUS', type: 'string' },
        { name: 'TEL', type: 'string' },
        { name: 'USEWHEN', type: 'string' },
        { name: 'USEWHERE', type: 'string' },
        { name: 'CREATE_TIME', type: 'string' },
        { name: 'CREATE_USER', type: 'string' },
        { name: 'UPDATE_TIME', type: 'string' },
        { name: 'UPDATE_USER', type: 'string' },
        { name: 'UPDATE_IP', type: 'string' },
        { name: 'SIGNDATA', type: 'string' },
        { name: 'NEXT_USER', type: 'string' }
    ]
});