Ext.define('WEBAPP.model.PhVender', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'AGEN_NO', type: 'string' },
        { name: 'AGEN_NAMEC', type: 'string' },
        { name: 'AGEN_NAMEE', type: 'string' },
        { name: 'AGEN_ADD', type: 'string' },
        { name: 'AGEN_FAX', type: 'string' },
        { name: 'AGEN_TEL', type: 'string' },
        { name: 'AGEN_ACC', type: 'string' },
        { name: 'UNI_NO', type: 'string' },
        { name: 'AGEN_BOSS', type: 'string' },
        { name: 'REC_STATUS', type: 'string' },
        { name: 'EMAIL', type: 'string' },
        { name: 'EMAIL_1', type: 'string' },
        { name: 'AGEN_BANK', type: 'string' },
        { name: 'AGEN_SUB', type: 'string' },
        { name: 'CREATE_TIME', type: 'string' },
        { name: 'CREATE_USER', type: 'string' },
        { name: 'UPDATE_TIME', type: 'string' },
        { name: 'UPDATE_USER', type: 'string' },
        { name: 'UPDATE_IP', type: 'string' },
        { name: 'MAIN_INID', type: 'string' },
        { name: 'EASYNAME', type: 'string' },
        { name: 'MINODR_AMT', type: 'string' },
         { name: 'AGEN_FREETEL1', type: 'string' },
        { name: 'AGEN_FREETEL2', type: 'string' },
        { name: 'AGEN_ZIP', type: 'string' },
        { name: 'AGEN_ZIP1', type: 'string' },
        { name: 'AGEN_ZIP2', type: 'string' },
        { name: 'AGEN_ADD1', type: 'string' },
        { name: 'AGEN_ADD2', type: 'string' },
        { name: 'AGEN_CONTACT', type: 'string' },
        { name: 'AGEN_CONTACT1', type: 'string' },
        { name: 'AGEN_CONTACT2', type: 'string' },
        { name: 'AGEN_CONCELL', type: 'string' },
        { name: 'AGEN_CONCELL1', type: 'string' },
        { name: 'AGEN_CONCELL2', type: 'string' },
        { name: 'AGEN_TEL2', type: 'string' },
        { name: 'AGEN_TEL3', type: 'string' },
        { name: 'AGEN_TEL4', type: 'string' },
        { name: 'AGEN_FAX2', type: 'string' },
        { name: 'AGEN_FAX3', type: 'string' },
        { name: 'AGEN_FAX4', type: 'string' },
        { name: 'AGEN_WEB1', type: 'string' },
        { name: 'AGEN_WEB2', type: 'string' },
        { name: 'AGEN_BANK_14', type: 'string' },
        { name: 'PROCFEE', type: 'string' },
        { name: 'POSTFEE', type: 'string' },
        { name: 'ACCZIP', type: 'string' },
        { name: 'ACCADDRESS', type: 'string' },
        { name: 'ACCTEL', type: 'string' },
        { name: 'ACCCONTACT', type: 'string' },
        { name: 'ACCEMAIL', type: 'string' },
    ]
});