//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppVen.FileService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileService.IFileService")]
    public interface IFileService {
        
        // CODEGEN: 作業 UploadFile 未由 RPC 或文件所包裝，正在產生訊息合約。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/UploadFile", ReplyAction="http://tempuri.org/IFileService/UploadFileResponse")]
        WebAppVen.FileService.UploadFileResponse UploadFile(WebAppVen.FileService.RemoteFileInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/UploadFile", ReplyAction="http://tempuri.org/IFileService/UploadFileResponse")]
        System.Threading.Tasks.Task<WebAppVen.FileService.UploadFileResponse> UploadFileAsync(WebAppVen.FileService.RemoteFileInfo request);
        
        // CODEGEN: 訊息 DownloadRequest 的包裝函式名稱 (DownloadRequest) 與預設值 (DownloadFile) 不符，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/DownloadFile", ReplyAction="http://tempuri.org/IFileService/DownloadFileResponse")]
        WebAppVen.FileService.RemoteFileInfo DownloadFile(WebAppVen.FileService.DownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/DownloadFile", ReplyAction="http://tempuri.org/IFileService/DownloadFileResponse")]
        System.Threading.Tasks.Task<WebAppVen.FileService.RemoteFileInfo> DownloadFileAsync(WebAppVen.FileService.DownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/DeleteFile", ReplyAction="http://tempuri.org/IFileService/DeleteFileResponse")]
        int DeleteFile(string file_guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/DeleteFile", ReplyAction="http://tempuri.org/IFileService/DeleteFileResponse")]
        System.Threading.Tasks.Task<int> DeleteFileAsync(string file_guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/CopyFile", ReplyAction="http://tempuri.org/IFileService/CopyFileResponse")]
        int CopyFile(string sub_dir, string file_guid, string file_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/CopyFile", ReplyAction="http://tempuri.org/IFileService/CopyFileResponse")]
        System.Threading.Tasks.Task<int> CopyFileAsync(string sub_dir, string file_guid, string file_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/CopyFileByFG", ReplyAction="http://tempuri.org/IFileService/CopyFileByFGResponse")]
        int CopyFileByFG(string old_file_guid, string new_file_guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/CopyFileByFG", ReplyAction="http://tempuri.org/IFileService/CopyFileByFGResponse")]
        System.Threading.Tasks.Task<int> CopyFileByFGAsync(string old_file_guid, string new_file_guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/TestService", ReplyAction="http://tempuri.org/IFileService/TestServiceResponse")]
        string TestService(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/TestService", ReplyAction="http://tempuri.org/IFileService/TestServiceResponse")]
        System.Threading.Tasks.Task<string> TestServiceAsync(string input);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoteFileInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoteFileInfo {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long Length;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public RemoteFileInfo() {
        }
        
        public RemoteFileInfo(string FileName, long Length, System.IO.Stream FileByteStream) {
            this.FileName = FileName;
            this.Length = Length;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileResponse {
        
        public UploadFileResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string FileName;
        
        public DownloadRequest() {
        }
        
        public DownloadRequest(string FileName) {
            this.FileName = FileName;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileServiceChannel : WebAppVen.FileService.IFileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileServiceClient : System.ServiceModel.ClientBase<WebAppVen.FileService.IFileService>, WebAppVen.FileService.IFileService {
        
        public FileServiceClient() {
        }
        
        public FileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppVen.FileService.UploadFileResponse WebAppVen.FileService.IFileService.UploadFile(WebAppVen.FileService.RemoteFileInfo request) {
            return base.Channel.UploadFile(request);
        }
        
        public void UploadFile(string FileName, long Length, System.IO.Stream FileByteStream) {
            WebAppVen.FileService.RemoteFileInfo inValue = new WebAppVen.FileService.RemoteFileInfo();
            inValue.FileName = FileName;
            inValue.Length = Length;
            inValue.FileByteStream = FileByteStream;
            WebAppVen.FileService.UploadFileResponse retVal = ((WebAppVen.FileService.IFileService)(this)).UploadFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAppVen.FileService.UploadFileResponse> WebAppVen.FileService.IFileService.UploadFileAsync(WebAppVen.FileService.RemoteFileInfo request) {
            return base.Channel.UploadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAppVen.FileService.UploadFileResponse> UploadFileAsync(string FileName, long Length, System.IO.Stream FileByteStream) {
            WebAppVen.FileService.RemoteFileInfo inValue = new WebAppVen.FileService.RemoteFileInfo();
            inValue.FileName = FileName;
            inValue.Length = Length;
            inValue.FileByteStream = FileByteStream;
            return ((WebAppVen.FileService.IFileService)(this)).UploadFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppVen.FileService.RemoteFileInfo WebAppVen.FileService.IFileService.DownloadFile(WebAppVen.FileService.DownloadRequest request) {
            return base.Channel.DownloadFile(request);
        }
        
        public long DownloadFile(ref string FileName, out System.IO.Stream FileByteStream) {
            WebAppVen.FileService.DownloadRequest inValue = new WebAppVen.FileService.DownloadRequest();
            inValue.FileName = FileName;
            WebAppVen.FileService.RemoteFileInfo retVal = ((WebAppVen.FileService.IFileService)(this)).DownloadFile(inValue);
            FileName = retVal.FileName;
            FileByteStream = retVal.FileByteStream;
            return retVal.Length;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAppVen.FileService.RemoteFileInfo> WebAppVen.FileService.IFileService.DownloadFileAsync(WebAppVen.FileService.DownloadRequest request) {
            return base.Channel.DownloadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAppVen.FileService.RemoteFileInfo> DownloadFileAsync(string FileName) {
            WebAppVen.FileService.DownloadRequest inValue = new WebAppVen.FileService.DownloadRequest();
            inValue.FileName = FileName;
            return ((WebAppVen.FileService.IFileService)(this)).DownloadFileAsync(inValue);
        }
        
        public int DeleteFile(string file_guid) {
            return base.Channel.DeleteFile(file_guid);
        }
        
        public System.Threading.Tasks.Task<int> DeleteFileAsync(string file_guid) {
            return base.Channel.DeleteFileAsync(file_guid);
        }
        
        public int CopyFile(string sub_dir, string file_guid, string file_name) {
            return base.Channel.CopyFile(sub_dir, file_guid, file_name);
        }
        
        public System.Threading.Tasks.Task<int> CopyFileAsync(string sub_dir, string file_guid, string file_name) {
            return base.Channel.CopyFileAsync(sub_dir, file_guid, file_name);
        }
        
        public int CopyFileByFG(string old_file_guid, string new_file_guid) {
            return base.Channel.CopyFileByFG(old_file_guid, new_file_guid);
        }
        
        public System.Threading.Tasks.Task<int> CopyFileByFGAsync(string old_file_guid, string new_file_guid) {
            return base.Channel.CopyFileByFGAsync(old_file_guid, new_file_guid);
        }
        
        public string TestService(string input) {
            return base.Channel.TestService(input);
        }
        
        public System.Threading.Tasks.Task<string> TestServiceAsync(string input) {
            return base.Channel.TestServiceAsync(input);
        }
    }
}
