Ext.define('WEBAPP.model.MI_MAST', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'MMCODE', type: 'string' },
        { name: 'MMNAME_C', type: 'string' },
        { name: 'MMNAME_E', type: 'string' },
        { name: 'MAT_CLASS', type: 'string' },
        { name: 'BASE_UNIT', type: 'string' },
        { name: 'AUTO_APLID', type: 'string' },
        { name: 'M_STOREID', type: 'string' },
        { name: 'M_CONTID', type: 'string' },
        { name: 'M_IDKEY', type: 'string' },
        { name: 'M_INVKEY', type: 'string' },
        { name: 'M_NHIKEY', type: 'string' },
        { name: 'M_GOVKEY', type: 'string' },
        { name: 'M_VOLL', type: 'string' },
        { name: 'M_VOLW', type: 'string' },
        { name: 'M_VOLH', type: 'string' },
        { name: 'M_VOLC', type: 'string' },
        { name: 'M_SWAP', type: 'string' },
        { name: 'M_MATID', type: 'string' },
        { name: 'M_SUPPLYID', type: 'string' },
        { name: 'M_CONSUMID', type: 'string' },
        { name: 'M_PAYKIND', type: 'string' },
        { name: 'M_PAYID', type: 'string' },
        { name: 'M_TRNID', type: 'string' },
        { name: 'M_APPLYID', type: 'string' },
        { name: 'M_PHCTNCO', type: 'string' },
        { name: 'M_ENVDT', type: 'string' },
        { name: 'M_DISTUN', type: 'string' },
        { name: 'M_AGENNO', type: 'string' },
        { name: 'M_AGENLAB', type: 'string' },
        { name: 'M_PURUN', type: 'string' },
        { name: 'M_CONTPRICE', type: 'string' },
        { name: 'M_DISCPERC', type: 'string' },
        { name: 'E_SUPSTATUS', type: 'string' },
        { name: 'E_MANUFACT', type: 'string' },
        { name: 'E_IFPUBLIC', type: 'string' },
        { name: 'E_STOCKTYPE', type: 'string' },
        { name: 'E_SPECNUNIT', type: 'string' },
        { name: 'E_COMPUNIT', type: 'string' },
        { name: 'E_YRARMYNO', type: 'string' },
        { name: 'E_ITEMARMYNO', type: 'string' },
        { name: 'E_GPARMYNO', type: 'string' },
        { name: 'E_CLFARMYNO', type: 'string' },
        { name: 'E_CODATE', type: 'string' },
        { name: 'E_PRESCRIPTYPE', type: 'string' },
        { name: 'E_DRUGCLASS', type: 'string' },
        { name: 'E_DRUGCLASSIFY', type: 'string' },
        { name: 'E_DRUGFORM', type: 'string' },
        { name: 'E_COMITMEMO', type: 'string' },
        { name: 'E_COMITCODE', type: 'string' },
        { name: 'E_INVFLAG', type: 'string' },
        { name: 'E_PURTYPE', type: 'string' },
        { name: 'E_SOURCECODE', type: 'string' },
        { name: 'E_DRUGAPLTYPE', type: 'string' },
        { name: 'E_ARMYORDCODE', type: 'string' },
        { name: 'E_PARCODE', type: 'string' },
        { name: 'E_PARORDCODE', type: 'string' },
        { name: 'E_SONTRANSQTY', type: 'string' },
        { name: 'CANCEL_ID', type: 'string' },
        { name: 'CREATE_TIME', type: 'string' },
        { name: 'CREATE_USER', type: 'string' },
        { name: 'UPDATE_TIME', type: 'string' },
        { name: 'UPDATE_USER', type: 'string' },
        { name: 'UPDATE_IP', type: 'string' },

        // =================== 湘倫 ======================
        { name: 'MMNAME', type: 'string' },     // 自訂 MMCODE + MMNAME_C
        // ===============================================
    ]
});