using System.Data;
using JCLib.DB;
using Dapper;
using MMSMSBAS.Models;
using System.Collections.Generic;

namespace MASTImport.Repository
{
    public class BASORDDRepository : JCLib.Mvc.BaseRepository
    {
        public BASORDDRepository(IUnitOfWork unitOfWork) : base(unitOfWork) { }

        public int DeleteAll()
        {
            string sql = "DELETE FROM MMSADM.HIS_BASORDD";
            return DBWork.Connection.Execute(sql, null, DBWork.Transaction);
        }

        public int Import(IList<BASORDDModels> basorddList)
        {
            string sql = @"INSERT INTO MMSADM.HIS_BASORDD (
   ORDERCODE, BEGINDATE, ENDDATE, 
   STOCKTRANSQTYO, STOCKTRANSQTYI, ATTACHTRANSQTYO, 
   ATTACHTRANSQTYI, INSUAMOUNT1, INSUAMOUNT2, 
   PAYAMOUNT1, PAYAMOUNT2, COSTAMOUNT, 
   MAMAGEFLAG, MAMAGERATE, INSUORDERCODE, 
   INSUSIGNI, INSUSIGNO, INSUEMGFLAG, 
   HOSPEMGFLAG, DENTALREFFLAG, PPFTYPE, 
   PPFPERCENTAGE, INSUKIDFLAG, HOSPKIDFLAG, 
   CONTRACTPRICE, CONTRACNO, SUPPLYNO, 
   CASEFROM, EXAMINEDISCFLAG, CREATEDATETIME, 
   CREATEOPID, PROCDATETIME, PROCOPID, 
   ORIGINALPRODUCER, AGENTNAME, ENDDATETIME, 
   EXECFLAG, DRUGCASEFROM, ARMYINSUORDERCODE, 
   ARMYINSUAMOUNT, PTRESOLUTIONCLASS, FDALICENSENO, 
   PRICE_T99) 
VALUES ( :ORDERCODE, :BEGINDATE, :ENDDATE, :STOCKTRANSQTYO,
 :STOCKTRANSQTYI, :ATTACHTRANSQTYO, :ATTACHTRANSQTYI,
 :INSUAMOUNT1, :INSUAMOUNT2, :PAYAMOUNT1, :PAYAMOUNT2,
 :COSTAMOUNT, :MAMAGEFLAG, :MAMAGERATE, :INSUORDERCODE,
 :INSUSIGNI, :INSUSIGNO, :INSUEMGFLAG, :HOSPEMGFLAG,
 :DENTALREFFLAG, :PPFTYPE, :PPFPERCENTAGE, :INSUKIDFLAG,
 :HOSPKIDFLAG, :CONTRACTPRICE, :CONTRACNO, :SUPPLYNO,
 :CASEFROM, :EXAMINEDISCFLAG, :CREATEDATETIME, :CREATEOPID,
 :PROCDATETIME, :PROCOPID, :ORIGINALPRODUCER, :AGENTNAME,
 :ENDDATETIME, :EXECFLAG, :DRUGCASEFROM, :ARMYINSUORDERCODE,
 :ARMYINSUAMOUNT, :PTRESOLUTIONCLASS, :FDALICENSENO, :PRICE_T99 )";
            return DBWork.Connection.Execute(sql, basorddList, DBWork.Transaction);
        }
    }
}