using System.Data;
using JCLib.DB;
using Dapper;
using MMSMSBAS.Models;
using System.Collections.Generic;

namespace MASTImport.Repository
{
    public class BASSTKARepository : JCLib.Mvc.BaseRepository
    {
        public BASSTKARepository(IUnitOfWork unitOfWork) : base(unitOfWork) { }

        public int DeleteAll()
        {
            string sql = "DELETE FROM MMSADM.HIS_STKDMIT";
            return DBWork.Connection.Execute(sql, null, DBWork.Transaction);
        }

        public int Import(IList<BASSTKAModels> basstkaList)
        {
            string sql = @"INSERT INTO MMSADM.HIS_STKDMIT (
   SKORDERCODE, DCMASSAGECODE, DMITDCCODE, 
   MANUFACTURER, WCOSTAMOUNT, PUBLICDRUGCODE, 
   STOCKUSECODE, SPECNUNIT, COMPONENTNUNIT, 
   YEARARMYNO, ITEMARMYNO, GROUPARMYNO, 
   CONTRACTEFFECTIVEDATE, MULTIPRESCRIPTIONCODE, DRUGCLASS, 
   DRUGCLASSIFY, DRUGFORM, COMMITTEEMEMO, 
   COMMITTEECODE, INVENTORYFLAG, APPLYUNIT, 
   PURCHASECASETYPE, MAXCURECONSISTENCY, MINCURECONSISTENCY, 
   PEARBEGIN, PEAREND, TROUGHBEGIN, 
   TROUGHEND, DANGERBEGIN, DANGEREND, 
   TDMMEMO1, TDMMEMO2, TDMMEMO3, 
   APPLYTRANSQTY, PURCHASETRANSQTY, CHINATTENTION, 
   ENGATTENTION, DRUGMEMO, CHINSIDEEFFECT, 
   ENGSIDEEFFECT, WARN, DOHSYMPTOM, 
   FDASYMPTOM, SUCKLESECURITY, PREGNANTGRADE, 
   DRUGEXTERIOR, PURCHASEUNIT, STOCKSOURCECODE, 
   MAMAGEFLAG, MAMAGERATE, DRUGFLAG, 
   FIRSTPURCHASEDATE, CREATEDATETIME, CREATEOPID, 
   PROCDATETIME, PROCOPID, DCMASSAGEMEMO, 
   DRUGLEAFLETLINK, DRUGPICTURELINK, COMPONENTNUNIT2, 
   COMPONENTNUNIT3, COMPONENTNUNIT4, DRUGENGEXTERIOR, 
   DRUGAPPLYTYPE, ARMYORDERCODE, PARENTCODE, 
   PARENTORDERCODE, SONTRANSQTY, CLASSIFIEDARMYNO, 
   DRUGTOTALAMOUNT, DRUGTOTALAMOUNTUNIT, DRUGPACKAGE) 
VALUES ( :SKORDERCODE, :DCMASSAGECODE, :DMITDCCODE, :MANUFACTURER,
 :WCOSTAMOUNT, :PUBLICDRUGCODE, :STOCKUSECODE, :SPECNUNIT,
 :COMPONENTNUNIT, :YEARARMYNO, :ITEMARMYNO, :GROUPARMYNO,
 :CONTRACTEFFECTIVEDATE, :MULTIPRESCRIPTIONCODE, :DRUGCLASS,
 :DRUGCLASSIFY, :DRUGFORM, :COMMITTEEMEMO, :COMMITTEECODE,
 :INVENTORYFLAG, :APPLYUNIT, :PURCHASECASETYPE, :MAXCURECONSISTENCY,
 :MINCURECONSISTENCY, :PEARBEGIN, :PEAREND, :TROUGHBEGIN,
 :TROUGHEND, :DANGERBEGIN, :DANGEREND, :TDMMEMO1, :TDMMEMO2,
 :TDMMEMO3, :APPLYTRANSQTY, :PURCHASETRANSQTY, :CHINATTENTION,
 :ENGATTENTION, :DRUGMEMO, :CHINSIDEEFFECT, :ENGSIDEEFFECT,
 :WARN, :DOHSYMPTOM, :FDASYMPTOM, :SUCKLESECURITY, :PREGNANTGRADE,
 :DRUGEXTERIOR, :PURCHASEUNIT, :STOCKSOURCECODE, :MAMAGEFLAG,
 :MAMAGERATE, :DRUGFLAG, :FIRSTPURCHASEDATE, :CREATEDATETIME,
 :CREATEOPID, :PROCDATETIME, :PROCOPID, :DCMASSAGEMEMO,
 :DRUGLEAFLETLINK, :DRUGPICTURELINK, :COMPONENTNUNIT2,
 :COMPONENTNUNIT3, :COMPONENTNUNIT4, :DRUGENGEXTERIOR,
 :DRUGAPPLYTYPE, :ARMYORDERCODE, :PARENTCODE, :PARENTORDERCODE,
 :SONTRANSQTY, :CLASSIFIEDARMYNO, :DRUGTOTALAMOUNT,
 :DRUGTOTALAMOUNTUNIT, :DRUGPACKAGE )";
            return DBWork.Connection.Execute(sql, basstkaList, DBWork.Transaction);
        }
    }
}