using System.Data;
using JCLib.DB;
using Dapper;
using MMSMSBAS.Models;
using System.Collections.Generic;

namespace DLLImport.Repository
{
    public class BASORDMRepository : JCLib.Mvc.BaseRepository
    {
        public BASORDMRepository(IUnitOfWork unitOfWork) : base(unitOfWork) { }

        public int DeleteAll()
        {
            string sql = "DELETE FROM MMSADM.HIS_BASORDM";
            return DBWork.Connection.Execute(sql, null, DBWork.Transaction);
        }

        public int Import(IList<BASORDMModels> basordmList)
        {
            string sql = @"INSERT INTO MMSADM.HIS_BASORDM (
   ORDERCODE, ORDERENGNAME, ORDERCHINNAME, 
   SCIENTIFICNAME, ORDERUNIT, ORDERCHINUNIT, 
   ATTACHUNIT, STOCKUNIT, SKORDERCODE, 
   UDSERVICEFLAG, TAKEKIND, LIMITEDQTYO, 
   LIMITEDQTYI, BUYORDERFLAG, OPENDATE, 
   PUBLICDRUGFLAG, STARTDATE, ORDERHOSPNAME, 
   ORDEREASYNAME, INSUOFFERFLAG, DCL, 
   APPENDMATERIALFLAG, EXORDERFLAG, ORDERDCFLAG, 
   MAXQTYPERTIME, MAXQTYPERDAY, MAXTAKETIMES, 
   DOHLICENSENO, RFIDCODE, PATHNO, 
   AGGREGATECODE, LIMITFLAG, RESTRICTCODE, 
   ANTIBIOTICSCODE, CARRYKINDI, CARRYKINDO, 
   UDPOWDERFLAG, RETURNDRUGFLAG, RESEARCHDRUGFLAG, 
   MACHINEFLAG, TRANSCOMPUTEFLAG, FIXPATHNOFLAG, 
   SYMPTOMCHIN, SYMPTOMENG, ONLYROUNDFLAG, 
   UNABLEPOWDERFLAG, DANGERDRUGFLAG, DANGERDRUGMEMO, 
   COLDSTORAGEFLAG, LIGHTAVOIDFLAG, CHANGESTATUS, 
   FREQNOO, FREQNOI, ORDERDAYS, 
   DOSE, HOSPCHARGEID1, HOSPCHARGEID2, 
   INSUCHARGEID1, INSUCHARGEID2, ORDERTYPE, 
   ORDERKIND, HIGHPRICEFLAG, CURETYPE, 
   INPDISPLAYFLAG, SOONCULLFLAG, SUBSTITUTE1, 
   SUBSTITUTE2, SUBSTITUTE3, SUBSTITUTE4, 
   SUBSTITUTE5, RELATEFLAGO, RELATEFLAGI, 
   WEIGHTTYPE, WEIGHTUNITLIMIT, RESTRICTTYPE, 
   MAXQTYO, MAXQTYI, MAXDAYSO, 
   MAXDAYSI, VALIDDAYSO, VALIDDAYSI, 
   CHECKINSWITCH, REPORTFLAG, SINGLEITEMFLAG, 
   OPERATIONFLAG, EXAMINEDRUGFLAG, MAINCUREITEM, 
   RAYPOSITION, CCORDERCODE, XRAYORDERCODE, 
   ISCURECODE, ORDIAGCODE, ORDERCODESORT, 
   SENDUNITFLAG, SIGNFLAG, EXCLUDEFLAG, 
   NEEDOPDTYPEFLAG, DRUGELEMCODE1, DRUGELEMCODE2, 
   DRUGELEMCODE3, DRUGELEMCODE4, CREATEDATETIME, 
   CREATEOPID, PROCDATETIME, PROCOPID, 
   CHANGEABLEFLAG, TDMFLAG, SPECIALORDERKIND, 
   NEEDREGIONFLAG, ORDERUSETYPE, FIXDOSEFLAG, 
   RAREDISORDERFLAG, HOSPEXAMINEFLAG, ORDERCONDCODE, 
   HOSPEXAMINEQTYFLAG, HEPATITISCODE, DRUGPARENTCODE1, 
   DRUGPARENTCODE2, DRUGPARENTCODE3, DRUGPARENTCODE4, 
   DRUGHOSPBEGINDATE, DRUGHOSPENDDATE, ZEROCASESTATE, 
   AIRDELIVERY, LIVERLIMITED, RENALLIMITED, 
   VACCINE, VACCINECLASS, BIOLOGICALAGENT, 
   BLOODPRODUCT, FREEZING, ORDERABLEDRUGFORM, 
   GERIATRIC, COSTEXCLUDECLASS, MILITARYEXCLUDECLASS, 
   SUBSTITUTE6, SUBSTITUTE7, SUBSTITUTE8, 
   SECTIONNO, SAFETYSYRINGE, ATCCODE1, 
   AHFSCODE1, ATCCODE2, AHFSCODE2, 
   ATCCODE3, AHFSCODE3, ATCCODE4, 
   AHFSCODE4, EXCEPTIONFLAG, BATCHNOFLAG, 
   EXCEPTIONCODE, MEDMAXFLAG, SUBSTITUTE9, 
   SUBSTITUTE10, SUBSTITUTE11, SUBSTITUTE12, 
   NSTSPECTYPE, NSTSPECTYPEFLAG, VPNIDNOFLAG, 
   FIRST_MACHINEKIND, OUT_MACHINEKIND, UD_MACHINEKIND, 
   PTPMACHINEFLAG) 
VALUES ( :ORDERCODE, :ORDERENGNAME, :ORDERCHINNAME, :SCIENTIFICNAME, :ORDERUNIT,
 :ORDERCHINUNIT, :ATTACHUNIT, :STOCKUNIT, :SKORDERCODE, :UDSERVICEFLAG, :TAKEKIND,
 :LIMITEDQTYO, :LIMITEDQTYI, :BUYORDERFLAG, :OPENDATE, :PUBLICDRUGFLAG, :STARTDATE,
 :ORDERHOSPNAME, :ORDEREASYNAME, :INSUOFFERFLAG, :DCL, :APPENDMATERIALFLAG,
 :EXORDERFLAG, :ORDERDCFLAG, :MAXQTYPERTIME, :MAXQTYPERDAY, :MAXTAKETIMES,
 :DOHLICENSENO, :RFIDCODE, :PATHNO, :AGGREGATECODE, :LIMITFLAG, :RESTRICTCODE,
 :ANTIBIOTICSCODE, :CARRYKINDI, :CARRYKINDO, :UDPOWDERFLAG, :RETURNDRUGFLAG,
 :RESEARCHDRUGFLAG, :MACHINEFLAG, :TRANSCOMPUTEFLAG, :FIXPATHNOFLAG, :SYMPTOMCHIN,
 :SYMPTOMENG, :ONLYROUNDFLAG, :UNABLEPOWDERFLAG, :DANGERDRUGFLAG, :DANGERDRUGMEMO,
 :COLDSTORAGEFLAG, :LIGHTAVOIDFLAG, :CHANGESTATUS, :FREQNOO, :FREQNOI, :ORDERDAYS,
 :DOSE, :HOSPCHARGEID1, :HOSPCHARGEID2, :INSUCHARGEID1, :INSUCHARGEID2, :ORDERTYPE,
 :ORDERKIND, :HIGHPRICEFLAG, :CURETYPE, :INPDISPLAYFLAG, :SOONCULLFLAG, :SUBSTITUTE1,
 :SUBSTITUTE2, :SUBSTITUTE3, :SUBSTITUTE4, :SUBSTITUTE5, :RELATEFLAGO, :RELATEFLAGI,
 :WEIGHTTYPE, :WEIGHTUNITLIMIT, :RESTRICTTYPE, :MAXQTYO, :MAXQTYI, :MAXDAYSO, :MAXDAYSI,
 :VALIDDAYSO, :VALIDDAYSI, :CHECKINSWITCH, :REPORTFLAG, :SINGLEITEMFLAG, :OPERATIONFLAG,
 :EXAMINEDRUGFLAG, :MAINCUREITEM, :RAYPOSITION, :CCORDERCODE, :XRAYORDERCODE, :ISCURECODE,
 :ORDIAGCODE, :ORDERCODESORT, :SENDUNITFLAG, :SIGNFLAG, :EXCLUDEFLAG, :NEEDOPDTYPEFLAG,
 :DRUGELEMCODE1, :DRUGELEMCODE2, :DRUGELEMCODE3, :DRUGELEMCODE4, :CREATEDATETIME,
 :CREATEOPID, :PROCDATETIME, :PROCOPID, :CHANGEABLEFLAG, :TDMFLAG, :SPECIALORDERKIND,
 :NEEDREGIONFLAG, :ORDERUSETYPE, :FIXDOSEFLAG, :RAREDISORDERFLAG, :HOSPEXAMINEFLAG,
 :ORDERCONDCODE, :HOSPEXAMINEQTYFLAG, :HEPATITISCODE, :DRUGPARENTCODE1, :DRUGPARENTCODE2,
 :DRUGPARENTCODE3, :DRUGPARENTCODE4, :DRUGHOSPBEGINDATE, :DRUGHOSPENDDATE, :ZEROCASESTATE,
 :AIRDELIVERY, :LIVERLIMITED, :RENALLIMITED, :VACCINE, :VACCINECLASS, :BIOLOGICALAGENT,
 :BLOODPRODUCT, :FREEZING, :ORDERABLEDRUGFORM, :GERIATRIC, :COSTEXCLUDECLASS,
 :MILITARYEXCLUDECLASS, :SUBSTITUTE6, :SUBSTITUTE7, :SUBSTITUTE8, :SECTIONNO, :SAFETYSYRINGE,
 :ATCCODE1, :AHFSCODE1, :ATCCODE2, :AHFSCODE2, :ATCCODE3, :AHFSCODE3, :ATCCODE4, :AHFSCODE4,
 :EXCEPTIONFLAG, :BATCHNOFLAG, :EXCEPTIONCODE, :MEDMAXFLAG, :SUBSTITUTE9, :SUBSTITUTE10,
 :SUBSTITUTE11, :SUBSTITUTE12, :NSTSPECTYPE, :NSTSPECTYPEFLAG, :VPNIDNOFLAG, :FIRST_MACHINEKIND,
 :OUT_MACHINEKIND, :UD_MACHINEKIND, :PTPMACHINEFLAG )";
            return DBWork.Connection.Execute(sql, basordmList, DBWork.Transaction);
        }
    }
}