using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MMSMSBAS.Models
{
    /// <summary>
    /// 介接HIS資料庫 BASORDM資料表(診療收費項目基本表主檔)
    /// </summary>
    public class BASORDMModels
    {
        public string ORDERCODE { get; set; } //1.院內碼
        public string ORDERENGNAME { get; set; } //2.院內碼英文名稱
        public string ORDERCHINNAME { get; set; } //3.院內碼中文名稱
        public string SCIENTIFICNAME { get; set; } //4.
        public string ORDERUNIT { get; set; } //5.
        public string ORDERCHINUNIT { get; set; } //6.
        public string ATTACHUNIT { get; set; } //7.
        public string STOCKUNIT { get; set; } //8.
        public string SKORDERCODE { get; set; } //9.
        public string UDSERVICEFLAG { get; set; } //10.
        public string TAKEKIND { get; set; } //11.
        public string LIMITEDQTYO { get; set; } //12.
        public string LIMITEDQTYI { get; set; } //13.
        public string BUYORDERFLAG { get; set; } //14.
        public string OPENDATE { get; set; } //15.
        public string PUBLICDRUGFLAG { get; set; } //16.
        public string STARTDATE { get; set; } //17.
        public string ORDERHOSPNAME { get; set; } //18.
        public string ORDEREASYNAME { get; set; } //19.
        public string INSUOFFERFLAG { get; set; } //20.
        public string DCL { get; set; } //21.
        public string APPENDMATERIALFLAG { get; set; } //22.
        public string EXORDERFLAG { get; set; } //23.
        public string ORDERDCFLAG { get; set; } //24.
        public string MAXQTYPERTIME { get; set; } //25.
        public string MAXQTYPERDAY { get; set; } //26.
        public string MAXTAKETIMES { get; set; } //27.
        public string DOHLICENSENO { get; set; } //28.
        public string RFIDCODE { get; set; } //29.
        public string PATHNO { get; set; } //30.
        public string AGGREGATECODE { get; set; } //31.
        public string LIMITFLAG { get; set; } //32.
        public string RESTRICTCODE { get; set; } //33.
        public string ANTIBIOTICSCODE { get; set; } //34.
        public string CARRYKINDI { get; set; } //35.
        public string CARRYKINDO { get; set; } //36.
        public string UDPOWDERFLAG { get; set; } //37.
        public string RETURNDRUGFLAG { get; set; } //38.
        public string RESEARCHDRUGFLAG { get; set; } //39.
        public string MACHINEFLAG { get; set; } //40.
        public string TRANSCOMPUTEFLAG { get; set; } //41.
        public string FIXPATHNOFLAG { get; set; } //42.
        public string SYMPTOMCHIN { get; set; } //43.
        public string SYMPTOMENG { get; set; } //44.
        public string ONLYROUNDFLAG { get; set; } //45.
        public string UNABLEPOWDERFLAG { get; set; } //46.
        public string DANGERDRUGFLAG { get; set; } //47.
        public string DANGERDRUGMEMO { get; set; } //48.
        public string COLDSTORAGEFLAG { get; set; } //49.
        public string LIGHTAVOIDFLAG { get; set; } //50.
        public string CHANGESTATUS { get; set; } //51.
        public string FREQNOO { get; set; } //52.
        public string FREQNOI { get; set; } //53.
        public string ORDERDAYS { get; set; } //54.
        public string DOSE { get; set; } //55.
        public string HOSPCHARGEID1 { get; set; } //56.
        public string HOSPCHARGEID2 { get; set; } //57.
        public string INSUCHARGEID1 { get; set; } //58.
        public string INSUCHARGEID2 { get; set; } //59.
        public string ORDERTYPE { get; set; } //60.
        public string ORDERKIND { get; set; } //61.
        public string HIGHPRICEFLAG { get; set; } //62.
        public string CURETYPE { get; set; } //63.
        public string INPDISPLAYFLAG { get; set; } //64.
        public string SOONCULLFLAG { get; set; } //65.
        public string SUBSTITUTE1 { get; set; } //66.
        public string SUBSTITUTE2 { get; set; } //67.
        public string SUBSTITUTE3 { get; set; } //68.
        public string SUBSTITUTE4 { get; set; } //69.
        public string SUBSTITUTE5 { get; set; } //70.
        public string RELATEFLAGO { get; set; } //71.
        public string RELATEFLAGI { get; set; } //72.
        public string WEIGHTTYPE { get; set; } //73.
        public string WEIGHTUNITLIMIT { get; set; } //74.
        public string RESTRICTTYPE { get; set; } //75.
        public string MAXQTYO { get; set; } //76.
        public string MAXQTYI { get; set; } //77.
        public string MAXDAYSO { get; set; } //78.
        public string MAXDAYSI { get; set; } //79.
        public string VALIDDAYSO { get; set; } //80.
        public string VALIDDAYSI { get; set; } //81.
        public string CHECKINSWITCH { get; set; } //82.
        public string REPORTFLAG { get; set; } //83.
        public string SINGLEITEMFLAG { get; set; } //84.
        public string OPERATIONFLAG { get; set; } //85.
        public string EXAMINEDRUGFLAG { get; set; } //86.
        public string MAINCUREITEM { get; set; } //87.
        public string RAYPOSITION { get; set; } //88.
        public string CCORDERCODE { get; set; } //89.
        public string XRAYORDERCODE { get; set; } //90.
        public string ISCURECODE { get; set; } //91.
        public string ORDIAGCODE { get; set; } //92.
        public string ORDERCODESORT { get; set; } //93.
        public string SENDUNITFLAG { get; set; } //94.
        public string SIGNFLAG { get; set; } //95.
        public string EXCLUDEFLAG { get; set; } //96.
        public string NEEDOPDTYPEFLAG { get; set; } //97.
        public string DRUGELEMCODE1 { get; set; } //98.
        public string DRUGELEMCODE2 { get; set; } //99.
        public string DRUGELEMCODE3 { get; set; } //100.
        public string DRUGELEMCODE4 { get; set; } //101.
        public string CREATEDATETIME { get; set; } //102.
        public string CREATEOPID { get; set; } //103.
        public string PROCDATETIME { get; set; } //104.
        public string PROCOPID { get; set; } //105.
        public string CHANGEABLEFLAG { get; set; } //106.
        public string TDMFLAG { get; set; } //107.
        public string SPECIALORDERKIND { get; set; } //108.
        public string NEEDREGIONFLAG { get; set; } //109.
        public string ORDERUSETYPE { get; set; } //110.
        public string FIXDOSEFLAG { get; set; } //111.
        public string RAREDISORDERFLAG { get; set; } //112.
        public string HOSPEXAMINEFLAG { get; set; } //113.
        public string ORDERCONDCODE { get; set; } //114.
        public string HOSPEXAMINEQTYFLAG { get; set; } //115.
        public string HEPATITISCODE { get; set; } //116.
        public string DRUGPARENTCODE1 { get; set; } //117.
        public string DRUGPARENTCODE2 { get; set; } //118.
        public string DRUGPARENTCODE3 { get; set; } //
        public string DRUGPARENTCODE4 { get; set; } //
        public string DRUGHOSPBEGINDATE { get; set; } //
        public string DRUGHOSPENDDATE { get; set; } //
        public string ZEROCASESTATE { get; set; } //
        public string AIRDELIVERY { get; set; } //
        public string LIVERLIMITED { get; set; } //
        public string RENALLIMITED { get; set; } //
        public string VACCINE { get; set; } //
        public string VACCINECLASS { get; set; } //
        public string BIOLOGICALAGENT { get; set; } //
        public string BLOODPRODUCT { get; set; } //
        public string FREEZING { get; set; } //
        public string ORDERABLEDRUGFORM { get; set; } //
        public string GERIATRIC { get; set; } //
        public string COSTEXCLUDECLASS { get; set; } //
        public string MILITARYEXCLUDECLASS { get; set; } //
        public string SUBSTITUTE6 { get; set; } //
        public string SUBSTITUTE7 { get; set; } //
        public string SUBSTITUTE8 { get; set; } //
        public string SECTIONNO { get; set; } //
        public string SAFETYSYRINGE { get; set; } //
        public string ATCCODE1 { get; set; } //
        public string AHFSCODE1 { get; set; } //
        public string ATCCODE2 { get; set; } //
        public string AHFSCODE2 { get; set; } //
        public string ATCCODE3 { get; set; } //
        public string AHFSCODE3 { get; set; } //
        public string ATCCODE4 { get; set; } //
        public string AHFSCODE4 { get; set; } //
        public string EXCEPTIONFLAG { get; set; } //
        public string BATCHNOFLAG { get; set; } //
        public string EXCEPTIONCODE { get; set; } //
        public string MEDMAXFLAG { get; set; } //
        public string SUBSTITUTE9 { get; set; } //
        public string SUBSTITUTE10 { get; set; } //
        public string SUBSTITUTE11 { get; set; } //
        public string SUBSTITUTE12 { get; set; } //
        public string NSTSPECTYPE { get; set; } //
        public string NSTSPECTYPEFLAG { get; set; } //
        public string VPNIDNOFLAG { get; set; } //
        public string FIRST_MACHINEKIND { get; set; } //
        public string OUT_MACHINEKIND { get; set; } //
        public string UD_MACHINEKIND { get; set; } //
        public string PTPMACHINEFLAG { get; set; } //
        public string ORDERLIMITFLAG { get; set; } //資料庫後來新增
        public string INVSTOCK_FLAG { get; set; } //0525新增:扣庫否
    }
}
